title: QUANT-IQ Help Guide
description: Documentation for the QUANT-IQ financial analysis tool.
baseurl: "/QuantIQ"
url: "https://sieverett.github.io"
author: Silas Everett

# Use a dark mode theme from GitHub Pages
remote_theme: "pages-themes/slate@v0.2.0" # GitHub's Slate theme (dark)

# Custom settings
markdown: kramdown
highlighter: rouge

# Plugins for Jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Ensure the FAQ.md in /docs is processed
include:
  - docs/FAQ.md