OPENAI_API_KEY="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"
OPENAI_ASSISTANT_ID="asst_vsn0zvKp4OlmcaUmWXj6I2M6"